### ISSUE TITLE
EfficientNet-B0 증강 데이터셋 추가하여 학습

### ISSUE THREAD

**Issue by hanhee-cho** [pladata-encore/DA36-mini3-hairwego#19]
## 🌈 Success criteria
새로운 CNN 모델 EfficientNet-B0 전이학습

1. 전체 데이터 로드 -> val/test
2. 증강 학습 데이터 로드 -> train
3. Sequence Subclass 작성
4. Sequence 객체 생성
5. **EfficientNet B0 로드**
include_top=False로 설정하여 Fully Connected Layer(FC layer)를 제외하고 특성 추출에만 사용
6. **Custom Head 추가**
탈모 진단을 위한 맞춤 분류 레이어를 추가
8. **모델 컴파일** 
손실 함수, 옵티마이저 등을 설정

## 👷 To-do
- [x] 특성 추출층 고정 >> Top (Custom Classification Head 추가)
- [x] Class weight 적용
- [x] Fine Tuning
- [x] 모델 컴파일
- [x] 콜백 정의
- [x] 학습
- [x] 학습 결과 시각화
- [x] 평가 / 모델 저장

## 🧶 Review
