### ISSUE TITLE
데이터 파일 로드 / 분할

### ISSUE THREAD

**Issue by hanhee-cho** [pladata-encore/DA36-mini3-hairwego#6]
## 🌈 Success criteria
1. Training 데이터 파일 (1.25G)  로드 >>> zip 해제 
2. 데이터 분할 >>> train : validation : test = 80 : 10 : 10

## 👷 To-do
- [x] 구글드라이브 파일 업로드 >>> 전체 공유 설정
- [x] 데이터 로드 후 >>> 메타데이터 생성 (이미지 디렉토리 / 라벨 데이터)
- [x] Class명(0~3) >>> int 변환
- [x] 데이터 분할 >>> train : validation : test = 80 : 10 : 10
