### ISSUE TITLE
ResNet 모델 - 데이터 분할 전 resize 진행

### ISSUE THREAD

**Issue by hanhee-cho** [pladata-encore/DA36-mini3-hairwego#7]
## 🌈 Success criteria
1. 데이터 분할 전 (224, 224, 3) shape으로 이미지 resize 진행 
- 사용할 모델의  pretraining 데이터 사이즈가 (224, 224, 3)
- 용량 줄이기

## 👷 To-do
- [x] 결과 저장 리스트 생
- [x] 이미지 경로 리스트 반복 - 이미지 읽기
- [x] 최종 이미지 넘파이 배열로 저장

## 🧶 Review
![Image](https://github.com/user-attachments/assets/84110102-35d3-4037-9ab3-66d17d5019ff)
